#Terminal Console Monitor State
#Mon Jun 08 03:32:39 UTC 2026
cloudflared-set token YOUR_CLOUDFLARE_API_TOKEN
cloudflared-set zone YOUR_ZONE_ID
cloudflared-set record YOUR_DNS_RECORD_ID
cloudflared-set name play.example.com
cloudflared-set proxied false
cloudflared-set ttl 120
cloudflared-set interval 300